version: '3'

services:
  web:
    build: .
    command: gunicorn dinoauth.wsgi:application --bind 0.0.0.0:8000 --workers 1
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  # postgres:
  #   image: postgres:11
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres